### ISSUE TITLE
Code usage

### ISSUE THREAD

**Issue by zainali84** [dride/cordova-plugin-rtsp-vlc#1]
Hi
I am new to using cordova. Can you please provide guide on how to use this library in detail. Currently i am using it as mentioned in readme but i am getting this error. 
[23:51:19]  typescript: /player/src/pages/home/home.ts, line: 14
            Property 'VideoPlayerVLC' does not exist on type 'Window'.

Thanks

**Comment by saoron** [comment]
You're probably using Ionic, Add this to 

    declare var VideoPlayerVLC: any;

On you Import list (Top of the page)
And call the method like this: 

    VideoPlayerVLC.play(..)

**Comment by zainali84** [comment]
Thanks a lot it worked. 
I have one more query if you can help. I am getting full screen video but i want two videos playing simultaneously side by side without full screen. your help would be appreciated.

**Comment by saoron** [comment]
Hi, This feature is not supported. 
Closing..
