### ISSUE TITLE
App crashes random after open or close streams

### ISSUE THREAD

**Issue by ten80** [dride/cordova-plugin-rtsp-vlc#14]
I have a list with streams in my app and sometimes my app crashes after opening and closing a stream. Is there a way to find out why? I use my app only on a iPad Air 2.

And one more question. Is it possible to show a audio icon or something, if i play a rtsp audio stream? Because it feels weird when u see a hole black screen with no feedback that audio is playing.

By the way: sorry for my bad english.

I hope someone could help me :)

**Comment by saoron** [comment]
Hi, Could you paste the logs of the crash here?

**Comment by ten80** [comment]
Sorry for the late response. I dont know exactly how to get the logs of the crash and i'm a windows user, no skills with apples, but xcodes tells me that after the app crashes:

`Chalet`libvlc_MetadataCancel:
->  0x104d41de0 <+0>:  movq   0x58(%rdi), %rdi
    0x104d41de4 <+4>:  testq  %rdi, %rdi
    0x104d41de7 <+7>:  je     0x104d41dee               ; <+14> at libvlc.c:563
    0x104d41de9 <+9>:  jmp    0x104d5d780               ; playlist_preparser_Cancel at preparser.c:191
    0x104d41dee <+14>: retq   
`
________
This is my function. It works, the stream is also playing, but if i close the stream and reopen it sometimes the app crashes. But it crashes differently, sometimes i can open the stream 10 times in a row, but sometimes only twice :(

`  public openVideo(url){
VideoPlayerVLC.play(url, function () {
//this.tost('Video played');
}, function (e) {
//this.tost(JSON.stringify(e));
});
}`

**Comment by saoron** [comment]
This might be related to the stream itself, anyway I have no way to reproduce this, closing sorry. Let me know if you find anything that might fix this..

**Comment by ten80** [comment]
Ahm, sorry, but it also happens, if no stream is playing. If my stream is not avalible there is just a black window that opens. If i trigger the button 3 times, it also crashes with the same error, so you can test it ez ;)
