### ISSUE TITLE
Ahm, sorry, but it also happens, if no stream is playing. If my stream is not avalible there is just a black window that opens. If i trigger the button 3 times, it also crashes with the same error, so you can test it ez ;)

### ISSUE THREAD

**Issue by ten80** [dride/cordova-plugin-rtsp-vlc#15]
Ahm, sorry, but it also happens, if no stream is playing. If my stream is not avalible there is just a black window that opens. If i trigger the button 3 times, it also crashes with the same error, so you can test it ez ;)

_Originally posted by @ten80 in https://github.com/dride/cordova-plugin-rtsp-vlc/issues/14#issuecomment-451434555_

**Comment by saoron** [comment]
Hi, Sorry for not answering we're swamped right now and frankly the plugin works great for our needs, If anyone else want to help out it will be well appreciated.

**Comment by ten80** [comment]
Hello saoron ;) Just a question, would you try to help me, if i would pay you?

I made a quick gif of showing the problem with the crash at the end. Just to show it to you.

![screen recording 2019-01-09 at 22 09 07](https://user-images.githubusercontent.com/1903993/50928854-18f88e00-145c-11e9-892b-8c6bd60610c3.gif)

**Comment by saoron** [comment]
@ten80 , ping me an email please: saoron (at) gmail (dot) com
