### ISSUE TITLE
can not rotate to landscape 

### ISSUE THREAD

**Issue by san2roy** [dride/cordova-plugin-rtsp-vlc#3]
Hello

I am trying to play streaming video with it. its working fine but video is not rotating to landscape mode. any solution?

**Comment by saoron** [comment]
Hi, This is yet not supported..

**Comment by saoron** [comment]
Fixed in https://github.com/dride/cordova-plugin-rtsp-vlc/commit/94ebcfa2b3384b7a534813b5d8b933469b56eae6

**Comment by soesantos** [comment]
Bro, not works for android, pls help to update it

**Comment by saoron** [comment]
Moved to #19 , Thanks @soesantos ill have a look.

**Comment by ArunaPonnapalli** [comment]
Unable to rotate to landscape. Please help
