### ISSUE TITLE
Can it being used on ionic 3 project?

### ISSUE THREAD

**Issue by Xsur** [dride/cordova-plugin-rtsp-vlc#5]
i had been install the cordova plugin but it seems i can't run the function, can you help me?

i call the function like this

![image](https://user-images.githubusercontent.com/25731857/46389266-208cf600-c6fb-11e8-9367-155c97d0abf7.png)

and in the console show this

![image](https://user-images.githubusercontent.com/25731857/46389233-fb988300-c6fa-11e8-9b91-1c202e99bd0b.png)

**Comment by saoron** [comment]
Hi, Try this

`declare var VideoPlayerVLC: any;`


And call the functions with:

`VideoPlayerVLC.play(..`

**Comment by Xsur** [comment]
hey there, thks for your response i try that but not working, and after googling i find the solution u dunno why but when i try this its suddenly work, 😄 

`        window["VideoPlayerVLC"].play(
        "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov", (done => {
          console.log(done);
        }),error => {
          console.log('vlc error',error);
        });`

**Comment by Xsur** [comment]
Hey there, thks for your response and It's work... 😄 👍
