### ISSUE TITLE
Can't add plugin in my project

### ISSUE THREAD

**Issue by johnnyjong823** [dride/cordova-plugin-rtsp-vlc#9]
Hi dride

I use Vs2015 cordova to add the plugin
but it can't find this plugin
It said "Visual Studio Unable to parse the plugin.xml"

![image](https://user-images.githubusercontent.com/17687685/47060116-d9c0f500-d1fe-11e8-9aac-776d197d971f.png)

Can U help me?

Thanks
Johnny

**Comment by saoron** [comment]
Have you installed the plugin?

`
cordova plugin add cordova-plugin-rtsp-vlc
`

**Comment by johnnyjong823** [comment]
I can't install this plugin
vs2015 can't find.
